OPENQASM 2.0;
include "qelib1.inc";
qreg qubits[8];

h qubits[0];
h qubits[1];
h qubits[2];
h qubits[3];
t qubits[0];
tdg qubits[1];
t qubits[2];
tdg qubits[3];
cx qubits[0], qubits[4];
cx qubits[1], qubits[5];
cx qubits[2], qubits[6];
cx qubits[3], qubits[7];
t qubits[4];
tdg qubits[5];
t qubits[6];
tdg qubits[7];
ccx qubits[0], qubits[1], qubits[4];
ccx qubits[2], qubits[3], qubits[6];
h qubits[4];
h qubits[6];

h qubits[0];
t qubits[0];
cx qubits[0], qubits[1];
tdg qubits[1];
h qubits[2];
t qubits[2];
cx qubits[2], qubits[3];
tdg qubits[3];
cz qubits[1], qubits[5];
cz qubits[3], qubits[7];
ccx qubits[0], qubits[2], qubits[4];
t qubits[4];
tdg qubits[6];
cx qubits[4], qubits[5];
h qubits[5];
ccx qubits[1], qubits[3], qubits[6];
tdg qubits[0];
t qubits[7];
cx qubits[6], qubits[7];

h qubits[0];
t qubits[0];
cx qubits[0], qubits[1];
tdg qubits[1];
h qubits[2];
t qubits[2];
cx qubits[2], qubits[3];
tdg qubits[3];
cz qubits[1], qubits[5];
cz qubits[3], qubits[7];
ccx qubits[0], qubits[2], qubits[4];
t qubits[4];
tdg qubits[6];
cx qubits[4], qubits[5];
h qubits[5];
ccx qubits[1], qubits[3], qubits[6];
tdg qubits[0];
t qubits[7];
cx qubits[6], qubits[7];

h qubits[0];
t qubits[0];
cx qubits[0], qubits[1];
tdg qubits[1];
h qubits[2];
t qubits[2];
cx qubits[2], qubits[3];
tdg qubits[3];
cz qubits[1], qubits[5];
cz qubits[3], qubits[7];
ccx qubits[0], qubits[2], qubits[4];
t qubits[4];
tdg qubits[6];
cx qubits[4], qubits[5];
h qubits[5];
ccx qubits[1], qubits[3], qubits[6];
tdg qubits[0];
t qubits[7];
cx qubits[6], qubits[7];

h qubits[0];
t qubits[0];
cx qubits[0], qubits[1];
tdg qubits[1];
h qubits[2];
t qubits[2];
cx qubits[2], qubits[3];
tdg qubits[3];
cz qubits[1], qubits[5];
cz qubits[3], qubits[7];
ccx qubits[0], qubits[2], qubits[4];
t qubits[4];
tdg qubits[6];
cx qubits[4], qubits[5];
h qubits[5];
ccx qubits[1], qubits[3], qubits[6];
tdg qubits[0];
t qubits[7];
cx qubits[6], qubits[7];

h qubits[0];
t qubits[0];
cx qubits[0], qubits[1];
tdg qubits[1];
h qubits[2];
t qubits[2];
cx qubits[2], qubits[3];
tdg qubits[3];
cz qubits[1], qubits[5];
cz qubits[3], qubits[7];
ccx qubits[0], qubits[2], qubits[4];
t qubits[4];
tdg qubits[6];
cx qubits[4], qubits[5];
h qubits[5];
ccx qubits[1], qubits[3], qubits[6];
tdg qubits[0];
t qubits[7];
cx qubits[6], qubits[7];

h qubits[0];
h qubits[1];
h qubits[2];
h qubits[3];
t qubits[4];
tdg qubits[5];
h qubits[6];
s qubits[7];
